import { botCache } from '../../mod.ts';
import { sendMessage } from '../../deps.ts';

const options = [
    "anyway",
    "asshole",
    "back",
    "bag",
    "ballmer",
    "awesome",
    "bday",
    "because",
    "blackadder",
    "bm",
    "bucket",
    "bus",
    "bye",
    "caniuse",
    "chainsaw",
    "cocksplat",
    "cool",
    "cup",
    "dalton",
    "deraadt",
    "diabetes",
    "donut",
    "dosomething",
    "equity",
    "even",
    "everyone",
    "everything",
    "family",
    "fascinating",
    "field",
    "fewer",
    "flying",
    "ftfy",
    "fts",
    "fyyff",
    "gyf",
    "give",
    "greed",
    "holygrail",
    "horse",
    "idea",
    "immensity",
    "ing",
    "jinglebells",
    "keep",
    "keepcalm",
    "king",
    "legend",
    "life",
    "linus",
    "logs",
    "look",
    "looking",
    "madison",
    "maybe",
    "me",
    "mornin",
    "no",
    "nugget",
    "off",
    "off-with",
    "outside",
    "particular",
    "pink",
    "problem",
    "programmer",
    "pulp",
    "question",
    "ratarse",
    "retard",
    "ridiculous",
    "rockstar",
    "rtfm",
    "sake",
    "shakespeare",
    "shit",
    "shutup",
    "single",
    "thanks",
    "that",
    "think",
    "thinking",
    "thumbs",
    "this",
    "too",
    "tucker",
    "waste",
    "what",
    "xmas",
    "yoda",
    "you",
    "zayn",
    "zero"
];

botCache.commands.set(`fuck`, {
    name: `fuck`,
    description: "commands/fuck:DESCRIPTION",
    botChannelPermissions: ["SEND_MESSAGES"],
    execute: async function (message) {
        try {
            return sendMessage(message.channelID, "This command is underconstruction");

        } catch (error) {
            return sendMessage(
                message.channelID,
                "Attempt to tell someone to fuck off has failed!"
            )
        }
    }
})